[theme]

# Used to style primary interface elements. It's the color displayed most frequently across your app's
# screens and components. Examples of widgets using this color are st.slider and st.checkbox.
primaryColor = "#7f4737"

# Background color for the main container.
backgroundColor = "#f6f2ed"

# Used as the background for most widgets. Examples of widgets with this background are st.sidebar,
# st.text_input, st.date_input.
secondaryBackgroundColor =  "#b5aa99"

# Font color for the page.
textColor = "#090f14"

# The root font size (in pixels) for the app.
# This determines the overall scale of text and UI elements. This is a
# positive integer. If this isn't set, the font size will be 16px.
baseFontSize = 16

# One or more font sizes for h1-h6 headings.  This is a list of up to six
# font sizes (in rem units).
headingFontSizes = ["2.5rem", "2.0rem", "2.0rem"]
